const express = require("express");
const userRoute = require("./user.route");
const categoryRoute = require("./category.route");
const bookRoute = require("./book.route");
const busRoute = require("./bus.route");
const hotelRoute = require("./hotel.route");
const schoolRoute = require("./school.route");
const travelRoute = require("./travel.route");
const movieRoute = require("./movie.route");
const stationeryRoute = require("./stationery.route");
const pharmacyRoute = require("./pharmacy.route");
const musicRoute = require("./music.route");
const jewelleryRoute = require("./jewellery.route");
const groceryRoute = require("./grocery.route");
const studentRoute = require("./student.route");
const tokenRoute = require("./token.route");
const router = express.Router();

router.use("/user", userRoute);
router.use("/category" , categoryRoute);
router.use("/book" , bookRoute);
router.use("/bus", busRoute);
router.use("/hotel" , hotelRoute);
router.use("/school" , schoolRoute);
router.use("/travel" , travelRoute);
router.use("/movie" , movieRoute);
router.use("/stationery" , stationeryRoute);
router.use("/pharmacy" , pharmacyRoute);
router.use("/music" , musicRoute);
router.use("/jewellery" , jewelleryRoute);
router.use("/grocery" , groceryRoute);
router.use("/student" , studentRoute);
router.use("/token" , tokenRoute);

module.exports = router;